// Copyright (c) 2025 Half_nothing
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: email.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityAtcJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	ActivityName  string                 `protobuf:"bytes,3,opt,name=activityName,proto3" json:"activityName,omitempty"`
	ActivityTime  string                 `protobuf:"bytes,4,opt,name=activityTime,proto3" json:"activityTime,omitempty"`
	Facility      string                 `protobuf:"bytes,5,opt,name=facility,proto3" json:"facility,omitempty"`
	Frequency     string                 `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityAtcJoin) Reset() {
	*x = ActivityAtcJoin{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityAtcJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAtcJoin) ProtoMessage() {}

func (x *ActivityAtcJoin) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAtcJoin.ProtoReflect.Descriptor instead.
func (*ActivityAtcJoin) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityAtcJoin) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ActivityAtcJoin) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivityAtcJoin) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ActivityAtcJoin) GetActivityTime() string {
	if x != nil {
		return x.ActivityTime
	}
	return ""
}

func (x *ActivityAtcJoin) GetFacility() string {
	if x != nil {
		return x.Facility
	}
	return ""
}

func (x *ActivityAtcJoin) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

type ActivityAtcLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	ActivityName  string                 `protobuf:"bytes,3,opt,name=activityName,proto3" json:"activityName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityAtcLeave) Reset() {
	*x = ActivityAtcLeave{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityAtcLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAtcLeave) ProtoMessage() {}

func (x *ActivityAtcLeave) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAtcLeave.ProtoReflect.Descriptor instead.
func (*ActivityAtcLeave) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityAtcLeave) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ActivityAtcLeave) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivityAtcLeave) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

type ActivityPilotJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	ActivityName  string                 `protobuf:"bytes,3,opt,name=activityName,proto3" json:"activityName,omitempty"`
	ActivityTime  string                 `protobuf:"bytes,4,opt,name=activityTime,proto3" json:"activityTime,omitempty"`
	Callsign      string                 `protobuf:"bytes,5,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Aircraft      string                 `protobuf:"bytes,6,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityPilotJoin) Reset() {
	*x = ActivityPilotJoin{}
	mi := &file_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPilotJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPilotJoin) ProtoMessage() {}

func (x *ActivityPilotJoin) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPilotJoin.ProtoReflect.Descriptor instead.
func (*ActivityPilotJoin) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityPilotJoin) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ActivityPilotJoin) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivityPilotJoin) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ActivityPilotJoin) GetActivityTime() string {
	if x != nil {
		return x.ActivityTime
	}
	return ""
}

func (x *ActivityPilotJoin) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *ActivityPilotJoin) GetAircraft() string {
	if x != nil {
		return x.Aircraft
	}
	return ""
}

type ActivityPilotLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	ActivityName  string                 `protobuf:"bytes,3,opt,name=activityName,proto3" json:"activityName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityPilotLeave) Reset() {
	*x = ActivityPilotLeave{}
	mi := &file_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPilotLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPilotLeave) ProtoMessage() {}

func (x *ActivityPilotLeave) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPilotLeave.ProtoReflect.Descriptor instead.
func (*ActivityPilotLeave) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityPilotLeave) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ActivityPilotLeave) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ActivityPilotLeave) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

type ApplicationPassed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Contact       string                 `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationPassed) Reset() {
	*x = ApplicationPassed{}
	mi := &file_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationPassed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationPassed) ProtoMessage() {}

func (x *ApplicationPassed) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationPassed.ProtoReflect.Descriptor instead.
func (*ApplicationPassed) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{4}
}

func (x *ApplicationPassed) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ApplicationPassed) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ApplicationPassed) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ApplicationPassed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplicationPassed) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type ApplicationProcessing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationProcessing) Reset() {
	*x = ApplicationProcessing{}
	mi := &file_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationProcessing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationProcessing) ProtoMessage() {}

func (x *ApplicationProcessing) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationProcessing.ProtoReflect.Descriptor instead.
func (*ApplicationProcessing) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{5}
}

func (x *ApplicationProcessing) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ApplicationProcessing) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ApplicationProcessing) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ApplicationProcessing) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type ApplicationRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Contact       string                 `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationRejected) Reset() {
	*x = ApplicationRejected{}
	mi := &file_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationRejected) ProtoMessage() {}

func (x *ApplicationRejected) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationRejected.ProtoReflect.Descriptor instead.
func (*ApplicationRejected) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{6}
}

func (x *ApplicationRejected) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *ApplicationRejected) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ApplicationRejected) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ApplicationRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApplicationRejected) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type AtcRatingChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	NewValue      string                 `protobuf:"bytes,3,opt,name=newValue,proto3" json:"newValue,omitempty"`
	OldValue      string                 `protobuf:"bytes,4,opt,name=oldValue,proto3" json:"oldValue,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtcRatingChange) Reset() {
	*x = AtcRatingChange{}
	mi := &file_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtcRatingChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtcRatingChange) ProtoMessage() {}

func (x *AtcRatingChange) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtcRatingChange.ProtoReflect.Descriptor instead.
func (*AtcRatingChange) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{7}
}

func (x *AtcRatingChange) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *AtcRatingChange) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AtcRatingChange) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *AtcRatingChange) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *AtcRatingChange) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *AtcRatingChange) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type Banned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banned) Reset() {
	*x = Banned{}
	mi := &file_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banned) ProtoMessage() {}

func (x *Banned) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banned.ProtoReflect.Descriptor instead.
func (*Banned) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{8}
}

func (x *Banned) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *Banned) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Banned) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Banned) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Banned) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Banned) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type InstructorChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Instructor    string                 `protobuf:"bytes,4,opt,name=instructor,proto3" json:"instructor,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructorChange) Reset() {
	*x = InstructorChange{}
	mi := &file_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructorChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructorChange) ProtoMessage() {}

func (x *InstructorChange) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructorChange.ProtoReflect.Descriptor instead.
func (*InstructorChange) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{9}
}

func (x *InstructorChange) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *InstructorChange) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *InstructorChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InstructorChange) GetInstructor() string {
	if x != nil {
		return x.Instructor
	}
	return ""
}

func (x *InstructorChange) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *InstructorChange) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type KickedFromServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickedFromServer) Reset() {
	*x = KickedFromServer{}
	mi := &file_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickedFromServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickedFromServer) ProtoMessage() {}

func (x *KickedFromServer) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickedFromServer.ProtoReflect.Descriptor instead.
func (*KickedFromServer) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{10}
}

func (x *KickedFromServer) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *KickedFromServer) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *KickedFromServer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickedFromServer) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *KickedFromServer) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *KickedFromServer) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type PasswordChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordChange) Reset() {
	*x = PasswordChange{}
	mi := &file_email_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChange) ProtoMessage() {}

func (x *PasswordChange) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChange.ProtoReflect.Descriptor instead.
func (*PasswordChange) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{11}
}

func (x *PasswordChange) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *PasswordChange) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PasswordChange) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *PasswordChange) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PasswordChange) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type PasswordReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordReset) Reset() {
	*x = PasswordReset{}
	mi := &file_email_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordReset) ProtoMessage() {}

func (x *PasswordReset) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordReset.ProtoReflect.Descriptor instead.
func (*PasswordReset) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{12}
}

func (x *PasswordReset) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *PasswordReset) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PasswordReset) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *PasswordReset) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PasswordReset) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type PermissionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Permissions   string                 `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionChange) Reset() {
	*x = PermissionChange{}
	mi := &file_email_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionChange) ProtoMessage() {}

func (x *PermissionChange) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionChange.ProtoReflect.Descriptor instead.
func (*PermissionChange) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionChange) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *PermissionChange) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PermissionChange) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *PermissionChange) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *PermissionChange) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type RoleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Roles         string                 `protobuf:"bytes,3,opt,name=roles,proto3" json:"roles,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact       string                 `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleChange) Reset() {
	*x = RoleChange{}
	mi := &file_email_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleChange) ProtoMessage() {}

func (x *RoleChange) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleChange.ProtoReflect.Descriptor instead.
func (*RoleChange) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{14}
}

func (x *RoleChange) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *RoleChange) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *RoleChange) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *RoleChange) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RoleChange) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type TicketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Reply         string                 `protobuf:"bytes,4,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketReply) Reset() {
	*x = TicketReply{}
	mi := &file_email_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketReply) ProtoMessage() {}

func (x *TicketReply) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketReply.ProtoReflect.Descriptor instead.
func (*TicketReply) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{15}
}

func (x *TicketReply) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *TicketReply) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *TicketReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TicketReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEmail   string                 `protobuf:"bytes,1,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_email_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{16}
}

func (x *Welcome) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *Welcome) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_email_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{17}
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int32                  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCode) Reset() {
	*x = VerifyCode{}
	mi := &file_email_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCode) ProtoMessage() {}

func (x *VerifyCode) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCode.ProtoReflect.Descriptor instead.
func (*VerifyCode) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyCode) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *VerifyCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // 0 = success, 1 = code expired or not found, 2 = invalid code, 3 = unknown error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_email_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\ffsd_universe\"\xc7\x01\n" +
	"\x0fActivityAtcJoin\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\"\n" +
	"\factivityName\x18\x03 \x01(\tR\factivityName\x12\"\n" +
	"\factivityTime\x18\x04 \x01(\tR\factivityTime\x12\x1a\n" +
	"\bfacility\x18\x05 \x01(\tR\bfacility\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\tR\tfrequency\"j\n" +
	"\x10ActivityAtcLeave\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\"\n" +
	"\factivityName\x18\x03 \x01(\tR\factivityName\"\xc7\x01\n" +
	"\x11ActivityPilotJoin\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\"\n" +
	"\factivityName\x18\x03 \x01(\tR\factivityName\x12\"\n" +
	"\factivityTime\x18\x04 \x01(\tR\factivityTime\x12\x1a\n" +
	"\bcallsign\x18\x05 \x01(\tR\bcallsign\x12\x1a\n" +
	"\baircraft\x18\x06 \x01(\tR\baircraft\"l\n" +
	"\x12ActivityPilotLeave\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\"\n" +
	"\factivityName\x18\x03 \x01(\tR\factivityName\"\x97\x01\n" +
	"\x11ApplicationPassed\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\acontact\x18\x05 \x01(\tR\acontact\"y\n" +
	"\x15ApplicationProcessing\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x18\n" +
	"\acontact\x18\x04 \x01(\tR\acontact\"\x97\x01\n" +
	"\x13ApplicationRejected\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\acontact\x18\x05 \x01(\tR\acontact\"\xb3\x01\n" +
	"\x0fAtcRatingChange\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x1a\n" +
	"\bnewValue\x18\x03 \x01(\tR\bnewValue\x12\x1a\n" +
	"\boldValue\x18\x04 \x01(\tR\boldValue\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x06 \x01(\tR\acontact\"\x9e\x01\n" +
	"\x06Banned\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x06 \x01(\tR\acontact\"\xb4\x01\n" +
	"\x10InstructorChange\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"instructor\x18\x04 \x01(\tR\n" +
	"instructor\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x06 \x01(\tR\acontact\"\xa8\x01\n" +
	"\x10KickedFromServer\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x06 \x01(\tR\acontact\"\x86\x01\n" +
	"\x0ePasswordChange\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1c\n" +
	"\tuserAgent\x18\x05 \x01(\tR\tuserAgent\"\x85\x01\n" +
	"\rPasswordReset\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1c\n" +
	"\tuserAgent\x18\x05 \x01(\tR\tuserAgent\"\x9e\x01\n" +
	"\x10PermissionChange\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12 \n" +
	"\vpermissions\x18\x03 \x01(\tR\vpermissions\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x05 \x01(\tR\acontact\"\x8c\x01\n" +
	"\n" +
	"RoleChange\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x14\n" +
	"\x05roles\x18\x03 \x01(\tR\x05roles\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x18\n" +
	"\acontact\x18\x05 \x01(\tR\acontact\"m\n" +
	"\vTicketReply\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05reply\x18\x04 \x01(\tR\x05reply\"=\n" +
	"\aWelcome\x12 \n" +
	"\vtargetEmail\x18\x01 \x01(\tR\vtargetEmail\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\"(\n" +
	"\fSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\n" +
	"VerifyCode\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x05R\x03cid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\">\n" +
	"\x0eVerifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xb4\v\n" +
	"\x05Email\x12P\n" +
	"\x13SendActivityAtcJoin\x12\x1d.fsd_universe.ActivityAtcJoin\x1a\x1a.fsd_universe.SendResponse\x12R\n" +
	"\x14SendActivityAtcLeave\x12\x1e.fsd_universe.ActivityAtcLeave\x1a\x1a.fsd_universe.SendResponse\x12T\n" +
	"\x15SendActivityPilotJoin\x12\x1f.fsd_universe.ActivityPilotJoin\x1a\x1a.fsd_universe.SendResponse\x12V\n" +
	"\x16SendActivityPilotLeave\x12 .fsd_universe.ActivityPilotLeave\x1a\x1a.fsd_universe.SendResponse\x12T\n" +
	"\x15SendApplicationPassed\x12\x1f.fsd_universe.ApplicationPassed\x1a\x1a.fsd_universe.SendResponse\x12\\\n" +
	"\x19SendApplicationProcessing\x12#.fsd_universe.ApplicationProcessing\x1a\x1a.fsd_universe.SendResponse\x12X\n" +
	"\x17SendApplicationRejected\x12!.fsd_universe.ApplicationRejected\x1a\x1a.fsd_universe.SendResponse\x12P\n" +
	"\x13SendAtcRatingChange\x12\x1d.fsd_universe.AtcRatingChange\x1a\x1a.fsd_universe.SendResponse\x12>\n" +
	"\n" +
	"SendBanned\x12\x14.fsd_universe.Banned\x1a\x1a.fsd_universe.SendResponse\x12R\n" +
	"\x14SendInstructorChange\x12\x1e.fsd_universe.InstructorChange\x1a\x1a.fsd_universe.SendResponse\x12R\n" +
	"\x14SendKickedFromServer\x12\x1e.fsd_universe.KickedFromServer\x1a\x1a.fsd_universe.SendResponse\x12N\n" +
	"\x12SendPasswordChange\x12\x1c.fsd_universe.PasswordChange\x1a\x1a.fsd_universe.SendResponse\x12L\n" +
	"\x11SendPasswordReset\x12\x1b.fsd_universe.PasswordReset\x1a\x1a.fsd_universe.SendResponse\x12R\n" +
	"\x14SendPermissionChange\x12\x1e.fsd_universe.PermissionChange\x1a\x1a.fsd_universe.SendResponse\x12F\n" +
	"\x0eSendRoleChange\x12\x18.fsd_universe.RoleChange\x1a\x1a.fsd_universe.SendResponse\x12H\n" +
	"\x0fSendTicketReply\x12\x19.fsd_universe.TicketReply\x1a\x1a.fsd_universe.SendResponse\x12@\n" +
	"\vSendWelcome\x12\x15.fsd_universe.Welcome\x1a\x1a.fsd_universe.SendResponse\x12I\n" +
	"\x0fVerifyEmailCode\x12\x18.fsd_universe.VerifyCode\x1a\x1c.fsd_universe.VerifyResponseB\x15Z\x13src/interfaces/grpcb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_email_proto_goTypes = []any{
	(*ActivityAtcJoin)(nil),       // 0: fsd_universe.ActivityAtcJoin
	(*ActivityAtcLeave)(nil),      // 1: fsd_universe.ActivityAtcLeave
	(*ActivityPilotJoin)(nil),     // 2: fsd_universe.ActivityPilotJoin
	(*ActivityPilotLeave)(nil),    // 3: fsd_universe.ActivityPilotLeave
	(*ApplicationPassed)(nil),     // 4: fsd_universe.ApplicationPassed
	(*ApplicationProcessing)(nil), // 5: fsd_universe.ApplicationProcessing
	(*ApplicationRejected)(nil),   // 6: fsd_universe.ApplicationRejected
	(*AtcRatingChange)(nil),       // 7: fsd_universe.AtcRatingChange
	(*Banned)(nil),                // 8: fsd_universe.Banned
	(*InstructorChange)(nil),      // 9: fsd_universe.InstructorChange
	(*KickedFromServer)(nil),      // 10: fsd_universe.KickedFromServer
	(*PasswordChange)(nil),        // 11: fsd_universe.PasswordChange
	(*PasswordReset)(nil),         // 12: fsd_universe.PasswordReset
	(*PermissionChange)(nil),      // 13: fsd_universe.PermissionChange
	(*RoleChange)(nil),            // 14: fsd_universe.RoleChange
	(*TicketReply)(nil),           // 15: fsd_universe.TicketReply
	(*Welcome)(nil),               // 16: fsd_universe.Welcome
	(*SendResponse)(nil),          // 17: fsd_universe.SendResponse
	(*VerifyCode)(nil),            // 18: fsd_universe.VerifyCode
	(*VerifyResponse)(nil),        // 19: fsd_universe.VerifyResponse
}
var file_email_proto_depIdxs = []int32{
	0,  // 0: fsd_universe.Email.SendActivityAtcJoin:input_type -> fsd_universe.ActivityAtcJoin
	1,  // 1: fsd_universe.Email.SendActivityAtcLeave:input_type -> fsd_universe.ActivityAtcLeave
	2,  // 2: fsd_universe.Email.SendActivityPilotJoin:input_type -> fsd_universe.ActivityPilotJoin
	3,  // 3: fsd_universe.Email.SendActivityPilotLeave:input_type -> fsd_universe.ActivityPilotLeave
	4,  // 4: fsd_universe.Email.SendApplicationPassed:input_type -> fsd_universe.ApplicationPassed
	5,  // 5: fsd_universe.Email.SendApplicationProcessing:input_type -> fsd_universe.ApplicationProcessing
	6,  // 6: fsd_universe.Email.SendApplicationRejected:input_type -> fsd_universe.ApplicationRejected
	7,  // 7: fsd_universe.Email.SendAtcRatingChange:input_type -> fsd_universe.AtcRatingChange
	8,  // 8: fsd_universe.Email.SendBanned:input_type -> fsd_universe.Banned
	9,  // 9: fsd_universe.Email.SendInstructorChange:input_type -> fsd_universe.InstructorChange
	10, // 10: fsd_universe.Email.SendKickedFromServer:input_type -> fsd_universe.KickedFromServer
	11, // 11: fsd_universe.Email.SendPasswordChange:input_type -> fsd_universe.PasswordChange
	12, // 12: fsd_universe.Email.SendPasswordReset:input_type -> fsd_universe.PasswordReset
	13, // 13: fsd_universe.Email.SendPermissionChange:input_type -> fsd_universe.PermissionChange
	14, // 14: fsd_universe.Email.SendRoleChange:input_type -> fsd_universe.RoleChange
	15, // 15: fsd_universe.Email.SendTicketReply:input_type -> fsd_universe.TicketReply
	16, // 16: fsd_universe.Email.SendWelcome:input_type -> fsd_universe.Welcome
	18, // 17: fsd_universe.Email.VerifyEmailCode:input_type -> fsd_universe.VerifyCode
	17, // 18: fsd_universe.Email.SendActivityAtcJoin:output_type -> fsd_universe.SendResponse
	17, // 19: fsd_universe.Email.SendActivityAtcLeave:output_type -> fsd_universe.SendResponse
	17, // 20: fsd_universe.Email.SendActivityPilotJoin:output_type -> fsd_universe.SendResponse
	17, // 21: fsd_universe.Email.SendActivityPilotLeave:output_type -> fsd_universe.SendResponse
	17, // 22: fsd_universe.Email.SendApplicationPassed:output_type -> fsd_universe.SendResponse
	17, // 23: fsd_universe.Email.SendApplicationProcessing:output_type -> fsd_universe.SendResponse
	17, // 24: fsd_universe.Email.SendApplicationRejected:output_type -> fsd_universe.SendResponse
	17, // 25: fsd_universe.Email.SendAtcRatingChange:output_type -> fsd_universe.SendResponse
	17, // 26: fsd_universe.Email.SendBanned:output_type -> fsd_universe.SendResponse
	17, // 27: fsd_universe.Email.SendInstructorChange:output_type -> fsd_universe.SendResponse
	17, // 28: fsd_universe.Email.SendKickedFromServer:output_type -> fsd_universe.SendResponse
	17, // 29: fsd_universe.Email.SendPasswordChange:output_type -> fsd_universe.SendResponse
	17, // 30: fsd_universe.Email.SendPasswordReset:output_type -> fsd_universe.SendResponse
	17, // 31: fsd_universe.Email.SendPermissionChange:output_type -> fsd_universe.SendResponse
	17, // 32: fsd_universe.Email.SendRoleChange:output_type -> fsd_universe.SendResponse
	17, // 33: fsd_universe.Email.SendTicketReply:output_type -> fsd_universe.SendResponse
	17, // 34: fsd_universe.Email.SendWelcome:output_type -> fsd_universe.SendResponse
	19, // 35: fsd_universe.Email.VerifyEmailCode:output_type -> fsd_universe.VerifyResponse
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
