// Copyright (c) 2025 Half_nothing
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: email.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Email_SendActivityAtcJoin_FullMethodName       = "/fsd_universe.Email/SendActivityAtcJoin"
	Email_SendActivityAtcLeave_FullMethodName      = "/fsd_universe.Email/SendActivityAtcLeave"
	Email_SendActivityPilotJoin_FullMethodName     = "/fsd_universe.Email/SendActivityPilotJoin"
	Email_SendActivityPilotLeave_FullMethodName    = "/fsd_universe.Email/SendActivityPilotLeave"
	Email_SendApplicationPassed_FullMethodName     = "/fsd_universe.Email/SendApplicationPassed"
	Email_SendApplicationProcessing_FullMethodName = "/fsd_universe.Email/SendApplicationProcessing"
	Email_SendApplicationRejected_FullMethodName   = "/fsd_universe.Email/SendApplicationRejected"
	Email_SendAtcRatingChange_FullMethodName       = "/fsd_universe.Email/SendAtcRatingChange"
	Email_SendBanned_FullMethodName                = "/fsd_universe.Email/SendBanned"
	Email_SendUnbanned_FullMethodName              = "/fsd_universe.Email/SendUnbanned"
	Email_SendInstructorChange_FullMethodName      = "/fsd_universe.Email/SendInstructorChange"
	Email_SendKickedFromServer_FullMethodName      = "/fsd_universe.Email/SendKickedFromServer"
	Email_SendPasswordChange_FullMethodName        = "/fsd_universe.Email/SendPasswordChange"
	Email_SendPasswordReset_FullMethodName         = "/fsd_universe.Email/SendPasswordReset"
	Email_SendPermissionChange_FullMethodName      = "/fsd_universe.Email/SendPermissionChange"
	Email_SendRoleChange_FullMethodName            = "/fsd_universe.Email/SendRoleChange"
	Email_SendTicketReply_FullMethodName           = "/fsd_universe.Email/SendTicketReply"
	Email_SendWelcome_FullMethodName               = "/fsd_universe.Email/SendWelcome"
	Email_SendEmailChange_FullMethodName           = "/fsd_universe.Email/SendEmailChange"
	Email_VerifyEmailCode_FullMethodName           = "/fsd_universe.Email/VerifyEmailCode"
	Email_RemoveEmailCode_FullMethodName           = "/fsd_universe.Email/RemoveEmailCode"
)

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailClient interface {
	SendActivityAtcJoin(ctx context.Context, in *ActivityAtcJoin, opts ...grpc.CallOption) (*SendResponse, error)
	SendActivityAtcLeave(ctx context.Context, in *ActivityAtcLeave, opts ...grpc.CallOption) (*SendResponse, error)
	SendActivityPilotJoin(ctx context.Context, in *ActivityPilotJoin, opts ...grpc.CallOption) (*SendResponse, error)
	SendActivityPilotLeave(ctx context.Context, in *ActivityPilotLeave, opts ...grpc.CallOption) (*SendResponse, error)
	SendApplicationPassed(ctx context.Context, in *ApplicationPassed, opts ...grpc.CallOption) (*SendResponse, error)
	SendApplicationProcessing(ctx context.Context, in *ApplicationProcessing, opts ...grpc.CallOption) (*SendResponse, error)
	SendApplicationRejected(ctx context.Context, in *ApplicationRejected, opts ...grpc.CallOption) (*SendResponse, error)
	SendAtcRatingChange(ctx context.Context, in *AtcRatingChange, opts ...grpc.CallOption) (*SendResponse, error)
	SendBanned(ctx context.Context, in *Banned, opts ...grpc.CallOption) (*SendResponse, error)
	SendUnbanned(ctx context.Context, in *Unbanned, opts ...grpc.CallOption) (*SendResponse, error)
	SendInstructorChange(ctx context.Context, in *InstructorChange, opts ...grpc.CallOption) (*SendResponse, error)
	SendKickedFromServer(ctx context.Context, in *KickedFromServer, opts ...grpc.CallOption) (*SendResponse, error)
	SendPasswordChange(ctx context.Context, in *PasswordChange, opts ...grpc.CallOption) (*SendResponse, error)
	SendPasswordReset(ctx context.Context, in *PasswordReset, opts ...grpc.CallOption) (*SendResponse, error)
	SendPermissionChange(ctx context.Context, in *PermissionChange, opts ...grpc.CallOption) (*SendResponse, error)
	SendRoleChange(ctx context.Context, in *RoleChange, opts ...grpc.CallOption) (*SendResponse, error)
	SendTicketReply(ctx context.Context, in *TicketReply, opts ...grpc.CallOption) (*SendResponse, error)
	SendWelcome(ctx context.Context, in *Welcome, opts ...grpc.CallOption) (*SendResponse, error)
	SendEmailChange(ctx context.Context, in *EmailChange, opts ...grpc.CallOption) (*SendResponse, error)
	VerifyEmailCode(ctx context.Context, in *VerifyCode, opts ...grpc.CallOption) (*VerifyResponse, error)
	RemoveEmailCode(ctx context.Context, in *RemoveVerifyCode, opts ...grpc.CallOption) (*RemoveVerifyCodeResponse, error)
}

type emailClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailClient(cc grpc.ClientConnInterface) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) SendActivityAtcJoin(ctx context.Context, in *ActivityAtcJoin, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendActivityAtcJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendActivityAtcLeave(ctx context.Context, in *ActivityAtcLeave, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendActivityAtcLeave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendActivityPilotJoin(ctx context.Context, in *ActivityPilotJoin, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendActivityPilotJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendActivityPilotLeave(ctx context.Context, in *ActivityPilotLeave, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendActivityPilotLeave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendApplicationPassed(ctx context.Context, in *ApplicationPassed, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendApplicationPassed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendApplicationProcessing(ctx context.Context, in *ApplicationProcessing, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendApplicationProcessing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendApplicationRejected(ctx context.Context, in *ApplicationRejected, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendApplicationRejected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendAtcRatingChange(ctx context.Context, in *AtcRatingChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendAtcRatingChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendBanned(ctx context.Context, in *Banned, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendBanned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendUnbanned(ctx context.Context, in *Unbanned, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendUnbanned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendInstructorChange(ctx context.Context, in *InstructorChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendInstructorChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendKickedFromServer(ctx context.Context, in *KickedFromServer, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendKickedFromServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendPasswordChange(ctx context.Context, in *PasswordChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendPasswordChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendPasswordReset(ctx context.Context, in *PasswordReset, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendPermissionChange(ctx context.Context, in *PermissionChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendPermissionChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendRoleChange(ctx context.Context, in *RoleChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendRoleChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendTicketReply(ctx context.Context, in *TicketReply, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendTicketReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendWelcome(ctx context.Context, in *Welcome, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendEmailChange(ctx context.Context, in *EmailChange, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Email_SendEmailChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) VerifyEmailCode(ctx context.Context, in *VerifyCode, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, Email_VerifyEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) RemoveEmailCode(ctx context.Context, in *RemoveVerifyCode, opts ...grpc.CallOption) (*RemoveVerifyCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVerifyCodeResponse)
	err := c.cc.Invoke(ctx, Email_RemoveEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
// All implementations must embed UnimplementedEmailServer
// for forward compatibility.
type EmailServer interface {
	SendActivityAtcJoin(context.Context, *ActivityAtcJoin) (*SendResponse, error)
	SendActivityAtcLeave(context.Context, *ActivityAtcLeave) (*SendResponse, error)
	SendActivityPilotJoin(context.Context, *ActivityPilotJoin) (*SendResponse, error)
	SendActivityPilotLeave(context.Context, *ActivityPilotLeave) (*SendResponse, error)
	SendApplicationPassed(context.Context, *ApplicationPassed) (*SendResponse, error)
	SendApplicationProcessing(context.Context, *ApplicationProcessing) (*SendResponse, error)
	SendApplicationRejected(context.Context, *ApplicationRejected) (*SendResponse, error)
	SendAtcRatingChange(context.Context, *AtcRatingChange) (*SendResponse, error)
	SendBanned(context.Context, *Banned) (*SendResponse, error)
	SendUnbanned(context.Context, *Unbanned) (*SendResponse, error)
	SendInstructorChange(context.Context, *InstructorChange) (*SendResponse, error)
	SendKickedFromServer(context.Context, *KickedFromServer) (*SendResponse, error)
	SendPasswordChange(context.Context, *PasswordChange) (*SendResponse, error)
	SendPasswordReset(context.Context, *PasswordReset) (*SendResponse, error)
	SendPermissionChange(context.Context, *PermissionChange) (*SendResponse, error)
	SendRoleChange(context.Context, *RoleChange) (*SendResponse, error)
	SendTicketReply(context.Context, *TicketReply) (*SendResponse, error)
	SendWelcome(context.Context, *Welcome) (*SendResponse, error)
	SendEmailChange(context.Context, *EmailChange) (*SendResponse, error)
	VerifyEmailCode(context.Context, *VerifyCode) (*VerifyResponse, error)
	RemoveEmailCode(context.Context, *RemoveVerifyCode) (*RemoveVerifyCodeResponse, error)
	mustEmbedUnimplementedEmailServer()
}

// UnimplementedEmailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServer struct{}

func (UnimplementedEmailServer) SendActivityAtcJoin(context.Context, *ActivityAtcJoin) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendActivityAtcJoin not implemented")
}
func (UnimplementedEmailServer) SendActivityAtcLeave(context.Context, *ActivityAtcLeave) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendActivityAtcLeave not implemented")
}
func (UnimplementedEmailServer) SendActivityPilotJoin(context.Context, *ActivityPilotJoin) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendActivityPilotJoin not implemented")
}
func (UnimplementedEmailServer) SendActivityPilotLeave(context.Context, *ActivityPilotLeave) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendActivityPilotLeave not implemented")
}
func (UnimplementedEmailServer) SendApplicationPassed(context.Context, *ApplicationPassed) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendApplicationPassed not implemented")
}
func (UnimplementedEmailServer) SendApplicationProcessing(context.Context, *ApplicationProcessing) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendApplicationProcessing not implemented")
}
func (UnimplementedEmailServer) SendApplicationRejected(context.Context, *ApplicationRejected) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendApplicationRejected not implemented")
}
func (UnimplementedEmailServer) SendAtcRatingChange(context.Context, *AtcRatingChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAtcRatingChange not implemented")
}
func (UnimplementedEmailServer) SendBanned(context.Context, *Banned) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBanned not implemented")
}
func (UnimplementedEmailServer) SendUnbanned(context.Context, *Unbanned) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendUnbanned not implemented")
}
func (UnimplementedEmailServer) SendInstructorChange(context.Context, *InstructorChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInstructorChange not implemented")
}
func (UnimplementedEmailServer) SendKickedFromServer(context.Context, *KickedFromServer) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendKickedFromServer not implemented")
}
func (UnimplementedEmailServer) SendPasswordChange(context.Context, *PasswordChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPasswordChange not implemented")
}
func (UnimplementedEmailServer) SendPasswordReset(context.Context, *PasswordReset) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPasswordReset not implemented")
}
func (UnimplementedEmailServer) SendPermissionChange(context.Context, *PermissionChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPermissionChange not implemented")
}
func (UnimplementedEmailServer) SendRoleChange(context.Context, *RoleChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRoleChange not implemented")
}
func (UnimplementedEmailServer) SendTicketReply(context.Context, *TicketReply) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTicketReply not implemented")
}
func (UnimplementedEmailServer) SendWelcome(context.Context, *Welcome) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWelcome not implemented")
}
func (UnimplementedEmailServer) SendEmailChange(context.Context, *EmailChange) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmailChange not implemented")
}
func (UnimplementedEmailServer) VerifyEmailCode(context.Context, *VerifyCode) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmailCode not implemented")
}
func (UnimplementedEmailServer) RemoveEmailCode(context.Context, *RemoveVerifyCode) (*RemoveVerifyCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveEmailCode not implemented")
}
func (UnimplementedEmailServer) mustEmbedUnimplementedEmailServer() {}
func (UnimplementedEmailServer) testEmbeddedByValue()               {}

// UnsafeEmailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServer will
// result in compilation errors.
type UnsafeEmailServer interface {
	mustEmbedUnimplementedEmailServer()
}

func RegisterEmailServer(s grpc.ServiceRegistrar, srv EmailServer) {
	// If the following call panics, it indicates UnimplementedEmailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Email_ServiceDesc, srv)
}

func _Email_SendActivityAtcJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityAtcJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendActivityAtcJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendActivityAtcJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendActivityAtcJoin(ctx, req.(*ActivityAtcJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendActivityAtcLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityAtcLeave)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendActivityAtcLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendActivityAtcLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendActivityAtcLeave(ctx, req.(*ActivityAtcLeave))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendActivityPilotJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityPilotJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendActivityPilotJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendActivityPilotJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendActivityPilotJoin(ctx, req.(*ActivityPilotJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendActivityPilotLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityPilotLeave)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendActivityPilotLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendActivityPilotLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendActivityPilotLeave(ctx, req.(*ActivityPilotLeave))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendApplicationPassed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationPassed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendApplicationPassed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendApplicationPassed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendApplicationPassed(ctx, req.(*ApplicationPassed))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendApplicationProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationProcessing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendApplicationProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendApplicationProcessing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendApplicationProcessing(ctx, req.(*ApplicationProcessing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendApplicationRejected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRejected)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendApplicationRejected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendApplicationRejected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendApplicationRejected(ctx, req.(*ApplicationRejected))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendAtcRatingChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AtcRatingChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendAtcRatingChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendAtcRatingChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendAtcRatingChange(ctx, req.(*AtcRatingChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banned)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendBanned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendBanned(ctx, req.(*Banned))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendUnbanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Unbanned)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendUnbanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendUnbanned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendUnbanned(ctx, req.(*Unbanned))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendInstructorChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstructorChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendInstructorChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendInstructorChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendInstructorChange(ctx, req.(*InstructorChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendKickedFromServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickedFromServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendKickedFromServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendKickedFromServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendKickedFromServer(ctx, req.(*KickedFromServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendPasswordChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendPasswordChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendPasswordChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendPasswordChange(ctx, req.(*PasswordChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordReset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendPasswordReset(ctx, req.(*PasswordReset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendPermissionChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendPermissionChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendPermissionChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendPermissionChange(ctx, req.(*PermissionChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendRoleChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendRoleChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendRoleChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendRoleChange(ctx, req.(*RoleChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendTicketReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendTicketReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendTicketReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendTicketReply(ctx, req.(*TicketReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Welcome)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendWelcome(ctx, req.(*Welcome))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendEmailChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendEmailChange(ctx, req.(*EmailChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_VerifyEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).VerifyEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_VerifyEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).VerifyEmailCode(ctx, req.(*VerifyCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_RemoveEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVerifyCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).RemoveEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_RemoveEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).RemoveEmailCode(ctx, req.(*RemoveVerifyCode))
	}
	return interceptor(ctx, in, info, handler)
}

// Email_ServiceDesc is the grpc.ServiceDesc for Email service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Email_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fsd_universe.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendActivityAtcJoin",
			Handler:    _Email_SendActivityAtcJoin_Handler,
		},
		{
			MethodName: "SendActivityAtcLeave",
			Handler:    _Email_SendActivityAtcLeave_Handler,
		},
		{
			MethodName: "SendActivityPilotJoin",
			Handler:    _Email_SendActivityPilotJoin_Handler,
		},
		{
			MethodName: "SendActivityPilotLeave",
			Handler:    _Email_SendActivityPilotLeave_Handler,
		},
		{
			MethodName: "SendApplicationPassed",
			Handler:    _Email_SendApplicationPassed_Handler,
		},
		{
			MethodName: "SendApplicationProcessing",
			Handler:    _Email_SendApplicationProcessing_Handler,
		},
		{
			MethodName: "SendApplicationRejected",
			Handler:    _Email_SendApplicationRejected_Handler,
		},
		{
			MethodName: "SendAtcRatingChange",
			Handler:    _Email_SendAtcRatingChange_Handler,
		},
		{
			MethodName: "SendBanned",
			Handler:    _Email_SendBanned_Handler,
		},
		{
			MethodName: "SendUnbanned",
			Handler:    _Email_SendUnbanned_Handler,
		},
		{
			MethodName: "SendInstructorChange",
			Handler:    _Email_SendInstructorChange_Handler,
		},
		{
			MethodName: "SendKickedFromServer",
			Handler:    _Email_SendKickedFromServer_Handler,
		},
		{
			MethodName: "SendPasswordChange",
			Handler:    _Email_SendPasswordChange_Handler,
		},
		{
			MethodName: "SendPasswordReset",
			Handler:    _Email_SendPasswordReset_Handler,
		},
		{
			MethodName: "SendPermissionChange",
			Handler:    _Email_SendPermissionChange_Handler,
		},
		{
			MethodName: "SendRoleChange",
			Handler:    _Email_SendRoleChange_Handler,
		},
		{
			MethodName: "SendTicketReply",
			Handler:    _Email_SendTicketReply_Handler,
		},
		{
			MethodName: "SendWelcome",
			Handler:    _Email_SendWelcome_Handler,
		},
		{
			MethodName: "SendEmailChange",
			Handler:    _Email_SendEmailChange_Handler,
		},
		{
			MethodName: "VerifyEmailCode",
			Handler:    _Email_VerifyEmailCode_Handler,
		},
		{
			MethodName: "RemoveEmailCode",
			Handler:    _Email_RemoveEmailCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
